logging:
  level: info
streams:
  - input:
      type: "generate"
      context: '{ "timestamp": 1625000000000, "value": 10, "sensor": "temp_1" }'
      interval: 1ns
      batch_size: 1
      count: 10
    pipeline:
      thread_num: 2
      processors:
        - type: "json_to_arrow"
        - type: "wasm"
          path: "examples/wasm/echo.wat"
          function: "transform"
    output:
      type: "stdout"
