/*
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The navigation is the product: five audience-facing areas (Get Started,
// Build, SQL, Operate, Reference, Develop) with curated ordering. Legacy
// routes are preserved by compatibility stub pages that are intentionally
// absent from this sidebar.

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'index',
    {type: 'category', label: 'Get Started', link: {type: 'doc', id: 'get-started/install'}, items: [
      'get-started/install', 'get-started/quickstart', 'get-started/durable-pipeline',
    ]},
    {type: 'category', label: 'Build', link: {type: 'doc', id: 'build/index'}, items: [
      'build/architecture', 'build/streams', 'build/jobs', 'build/distributed-jobs',
      {type: 'category', label: 'Data & Durability', items: [
        'build/metadata', 'build/backpressure', 'build/delivery-semantics',
        'build/wal', 'build/exactly-once',
      ]},
      {type: 'category', label: 'Components', link: {type: 'doc', id: 'components'}, items: [
        {type: 'autogenerated', dirName: 'components'},
      ]},
      {type: 'category', label: 'Recipes', link: {type: 'doc', id: 'build/recipes'}, items: [
        'build/recipes/kafka-to-sql',
        'build/recipes/cdc-debezium',
        'build/recipes/windowed-aggregation',
        'build/recipes/http-ingestion',
        'build/recipes/case-webhook-durable',
        'build/recipes/case-order-stream-sql',
        'build/recipes/case-telemetry-windows',
      ]},
    ]},
    {type: 'category', label: 'SQL Reference', link: {type: 'doc', id: 'sql'}, items: [
      'sql/data-types', 'sql/operators', 'sql/select', 'sql/subqueries',
      'sql/aggregate_functions', 'sql/window_functions', 'sql/scalar_functions',
      'sql/special_functions', 'sql/udf',
    ]},
    {type: 'category', label: 'Operate', link: {type: 'doc', id: 'operate/overview'}, items: [
      'operate/kubernetes', 'operate/rollout', 'operate/observability', 'operate/recovery', 'operate/tls-matrix',
      {type: 'category', label: 'Control Plane', link: {type: 'doc', id: 'operate/control-plane'}, items: [
        'operate/control-plane/overview', 'operate/control-plane/deploy',
        'operate/control-plane/console', 'operate/control-plane/operations',
        'operate/control-plane/reconciliation',
      ]},
    ]},
    {type: 'category', label: 'Reference', items: [
      'reference/cli', 'reference/api', 'reference/configuration', 'reference/ide-schema',
      'reference/component-inventory', 'reference/examples', 'reference/compatibility',
    ]},
    {type: 'category', label: 'Develop', link: {type: 'doc', id: 'develop/index'}, items: [
      'develop/kernel', 'develop/plugins', 'develop/s3-wal-performance',
    ]},
    {type: 'category', label: 'Migration', items: ['migration/routes']},
    {type: 'category', label: 'About', link: {type: 'doc', id: 'about/logo'}, items: [
      'about/logo',
    ]},
    'contribute',
  ],
};

export default sidebars;
