/*
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'start-here',
    'build-pipelines',
    {type: 'category', label: 'Understand ArkFlow', items: [
      'concepts/architecture', 'concepts/backpressure-ordering', 'concepts/metadata',
      'concepts/delivery-semantics', 'concepts/wal-optimization', 'concepts/exactly-once',
    ]},
    {type: 'category', label: 'Get started', items: [
      'getting-started/install', 'getting-started/quickstart',
    ]},
    {type: 'category', label: 'Components', items: [
      {type: 'autogenerated', dirName: 'components'},
    ]},
    {type: 'category', label: 'Configure', items: [
      'configuration/top-level', {type: 'autogenerated', dirName: 'sql'},
    ]},
    {type: 'category', label: 'Operate', items: [
      'operate', 'deploy/k8s-deployment', {type: 'autogenerated', dirName: 'control-plane'},
    ]},
    {type: 'category', label: 'Reference', items: ['reference/component-inventory', 'reference/examples', 'reference/compatibility']},
    {type: 'category', label: 'Migration', items: ['migration/routes']},
    'contribute',
  ],
};

export default sidebars;
