import { useCallback, useEffect, useState } from 'react'
import { api } from './api'
import { Snapshot } from './features'
import { Overview } from './features/overview'
import { Runtime } from './features/runtime'
import { Configuration } from './features/configuration'
import { Components } from './features/components'
import { Events } from './features/events'
import { Settings } from './features/settings'

type Page = 'overview'|'runtime'|'configuration'|'components'|'events'|'settings'
export function App(){
  const[page,setPage]=useState<Page>('overview');const[selectedNode,setSelectedNode]=useState(()=>new URLSearchParams(window.location.search).get('node_id')??'');const[snapshot,setSnapshot]=useState<Snapshot>({system:null,status:null,nodes:[],streams:[],operations:[],events:[]});const[error,setError]=useState('');const[stale,setStale]=useState(false)
  const refresh=useCallback(async()=>{try{const[system,status,nodes,streams,operations,events,metrics]=await Promise.all([api.system(),api.status().catch(()=>null),api.nodes().catch(()=>({items:[],page:1,page_size:0,total:0})),api.streams(selectedNode||undefined),api.operations(selectedNode||undefined),api.events(selectedNode||undefined),api.metrics(selectedNode||undefined).catch(()=>undefined)]);const nextOperations=(Array.isArray(operations)?operations:operations.items).filter(op=>op.operation);const rawNodes=Array.isArray(nodes)?nodes:nodes.items;const fleetNodes=rawNodes.filter(node=>typeof node==='object'&&node!==null&&'lease_expires_at_ms' in node);setSnapshot({system:{...system,capabilities:system.capabilities??[]},status:status??null,nodes:fleetNodes,streams:Array.isArray(streams)?streams:streams.items,operations:nextOperations,events:Array.isArray(events)?events:events.items,metrics});setStale(false);setError('')}catch(cause){setStale(true);setError(errorMessage(cause))}},[selectedNode])
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(timer)},[refresh])
  const selectedNodeState=snapshot.nodes.find(node=>node.id===selectedNode);const canMutate=!selectedNodeState||selectedNodeState.state==='online'
  const command=async(id:string,action:'start'|'stop'|'restart')=>{try{const operation=await api.command(id,action,selectedNode||undefined);await waitForOperation(operation.id);await refresh()}catch(cause){setError(errorMessage(cause))}}
  const nav:[Page,string][]=[['overview','Overview'],['runtime','Streams'],['configuration','Configuration'],['components','Components'],['events','Events'],['settings','Settings']]
  return <div className="shell"><aside><h1>arkflow</h1><p>Control plane</p><nav>{nav.map(([key,label])=><a key={key} className={page===key?'active':''} onClick={()=>setPage(key)}>{label}</a>)}</nav></aside><main><header><div><span className="eyebrow">CONTROL PLANE</span><h2>{page}</h2></div><div className="actions"><select aria-label="Compute node" value={selectedNode} onChange={event=>{const value=event.target.value;setSelectedNode(value);const params=new URLSearchParams(window.location.search);if(value)params.set('node_id',value);else params.delete('node_id');window.history.replaceState(null,'',`${window.location.pathname}${params.toString()?`?${params}`:''}`)}}><option value="">All nodes</option>{snapshot.nodes.map(node=><option key={node.id} value={node.id}>{node.id} · {node.state}</option>)}</select><button onClick={()=>void refresh()}>Refresh</button></div></header>{selectedNodeState&&selectedNodeState.state!=='online'&&<div className="warning">Node {selectedNode} is {selectedNodeState.state}; mutating actions are disabled.</div>}{stale&&<div className="warning">Showing the last known state. Retry when the control API is available.</div>}{error&&<div className="error">{error}</div>}{page==='overview'&&<Overview snapshot={snapshot}/>} {page==='runtime'&&<Runtime streams={snapshot.streams} operations={snapshot.operations} events={snapshot.events} command={command} canMutate={canMutate}/>} {page==='configuration'&&<Configuration onError={setError} nodeId={selectedNode||undefined}/>} {page==='components'&&<Components onError={setError}/>} {page==='events'&&<Events events={snapshot.events}/>} {page==='settings'&&<Settings status={snapshot.status}/>}</main></div>
}
async function waitForOperation(id:string){for(let i=0;i<30;i++){const operation=await api.operation(id);if(['succeeded','failed','cancelled','timed_out','node_unavailable'].includes(operation.state)){if(operation.state!=='succeeded')throw new Error(operation.error??`Operation ${operation.state}`);return}await new Promise(resolve=>window.setTimeout(resolve,250))}throw new Error('Operation timed out')}
function errorMessage(cause:unknown){return typeof cause==='object'&&cause&&'message'in cause?String(cause.message):cause instanceof Error?cause.message:'Control API unavailable'}
