import { useCallback, useEffect, useState } from 'react'
import { api, ApiError, ControlNode, streamEvents, waitForOperation } from './api'
import { Snapshot } from './features'
import { Overview } from './features/overview'
import { Runtime } from './features/runtime'
import { Configuration } from './features/configuration'
import { Components } from './features/components'
import { Events } from './features/events'
import { Settings } from './features/settings'
import { Rollouts } from './features/rollouts'

type Page = 'overview'|'runtime'|'configuration'|'rollouts'|'components'|'events'|'settings'
export function App(){
  const[page,setPage]=useState<Page>('overview');const[selectedNode,setSelectedNode]=useState(()=>new URLSearchParams(window.location.search).get('node_id')??'');const[snapshot,setSnapshot]=useState<Snapshot>({system:null,status:null,nodes:[],streams:[],operations:[],events:[]});const[error,setError]=useState('');const[stale,setStale]=useState(false);const[live,setLive]=useState(false)
  const refresh=useCallback(async()=>{try{const[system,status,nodes,streams,operations,events,metrics]=await Promise.all([api.system(),api.status().catch(()=>null),api.nodes(),api.streams(selectedNode||undefined),api.operations(selectedNode||undefined),api.events(selectedNode||undefined),api.metrics(selectedNode||undefined).catch(()=>undefined)]);setSnapshot({system,status:status??null,nodes:nodes.items as ControlNode[],streams:streams.items,operations:operations.items,events:events.items,metrics});setStale(false);setError('')}catch(cause){setStale(true);setError(errorMessage(cause))}},[selectedNode])
  useEffect(()=>{void refresh();const timer=window.setInterval(()=>void refresh(),30000);const controller=streamEvents(()=>void refresh(),state=>setLive(state==='connected'),selectedNode||undefined);return()=>{window.clearInterval(timer);controller.abort()}},[refresh,selectedNode])
  const selectedNodeState=snapshot.nodes.find(node=>node.id===selectedNode);const canMutate=!selectedNodeState||selectedNodeState.state==='online'||selectedNodeState.state==='running'
  const command=async(id:string,action:'start'|'stop'|'restart')=>{try{const operation=await api.command(id,action,selectedNode||undefined);await waitForOperation(operation.id);await refresh()}catch(cause){setError(errorMessage(cause))}}
  const nav:[Page,string][]=[['overview','Overview'],['runtime','Streams'],['configuration','Configuration'],['rollouts','Rollouts'],['components','Components'],['events','Events'],['settings','Settings']]
  return <div className="shell"><aside><h1>arkflow</h1><p>Control plane</p><nav>{nav.map(([key,label])=><a key={key} className={page===key?'active':''} onClick={()=>setPage(key)}>{label}</a>)}</nav></aside><main><header><div><span className="eyebrow">CONTROL PLANE</span><h2>{page}</h2></div><div className="actions"><span className={`connection ${live?'connected':'disconnected'}`}>{live?'Live events':'Snapshot mode'}</span><select aria-label="Compute node" value={selectedNode} onChange={event=>{const value=event.target.value;setSelectedNode(value);const params=new URLSearchParams(window.location.search);if(value)params.set('node_id',value);else params.delete('node_id');window.history.replaceState(null,'',`${window.location.pathname}${params.toString()?`?${params}`:''}`)}}><option value="">All nodes</option>{snapshot.nodes.map(node=><option key={node.id} value={node.id}>{node.id} · {node.state}</option>)}</select><button onClick={()=>void refresh()}>Refresh</button></div></header>{selectedNodeState&&selectedNodeState.state!=='online'&&selectedNodeState.state!=='running'&&<div className="warning">Node {selectedNode} is {selectedNodeState.state}; mutating actions are disabled.</div>}{stale&&<div className="warning">Showing the last known state. Retry when the control API is available.</div>}{error&&<div className="error">{error}</div>}{page==='overview'&&<Overview snapshot={snapshot}/>} {page==='runtime'&&<Runtime streams={snapshot.streams} operations={snapshot.operations} events={snapshot.events} command={command} canMutate={canMutate} onOperationChanged={()=>void refresh()}/>} {page==='configuration'&&<Configuration onError={setError} nodeId={selectedNode||undefined}/>} {page==='rollouts'&&<Rollouts nodes={snapshot.nodes} onError={setError}/>} {page==='components'&&<Components onError={setError}/>} {page==='events'&&<Events events={snapshot.events}/>} {page==='settings'&&<Settings status={snapshot.status}/>}</main></div>
}
function errorMessage(cause:unknown){if(typeof cause==='object'&&cause&&'message'in cause){const error=cause as ApiError;return `${error.message}${error.correlation_id?` (ref ${error.correlation_id})`:''}`}return cause instanceof Error?cause.message:'Control API unavailable'}
