import { useEffect, useState } from 'react'
import { api, Component, ConfigIssue, ConfigVersion, ControlEvent, EngineStatus, Operation, StreamStatus, SystemResource } from './api'

export type Snapshot = { system: SystemResource|null; status: EngineStatus|null; streams: StreamStatus[]; operations: Operation[]; events: ControlEvent[] }
export type Command = (id: string, action: 'start'|'stop'|'restart') => Promise<void>
export function Overview({snapshot}:{snapshot:Snapshot}){const s=snapshot.status;return <><section className="cards"><Card label="Control plane" value={snapshot.system?.state??'Loading…'}/><Card label="Nodes" value={snapshot.system?.node_count??'—'}/><Card label="Streams" value={s?.streams_total??'—'}/><Card label="Active operations" value={snapshot.system?.active_operations??'—'}/></section><section className="panel"><div className="panel-title"><h3>Operational summary</h3><span>{(snapshot.system?.capabilities??[]).join(' · ')}</span></div><p className="empty">This console manages runtime resources, configuration versions, component catalogue, and administrative operations.</p></section></>}
export function Runtime({streams,operations,command}:{streams:StreamStatus[];operations:Operation[];command:Command}){return <><section className="panel"><div className="panel-title"><h3>Stream runtimes</h3><span>{streams.length} resources</span></div>{streams.length===0?<p className="empty">No streams registered.</p>:streams.map(stream=><div className="row" key={stream.id}><div><strong>{stream.id}</strong><small>{stream.node_id??'local-node'} · {stream.desired_state??'unknown'} desired · {stream.metrics.input_messages} input messages · {stream.metrics.output_messages} output messages</small></div><span className={`state ${stream.state}`}>{stream.state}</span><div className="actions">{(['start','stop','restart'] as const).map(action=><button key={action} onClick={()=>{if(window.confirm(`${action} ${stream.id}?`))void command(stream.id,action)}}>{action[0].toUpperCase()+action.slice(1)}</button>)}</div></div>)}</section><section className="panel"><div className="panel-title"><h3>Administrative operations</h3><span>Async and idempotent</span></div>{operations.map(op=><p className="event-row" key={op.id}><strong>{op.id}</strong> {op.operation} · {op.state} · {op.progress}% {(['queued','running'].includes(op.state))&&<button onClick={()=>void api.cancel(op.id)}>Cancel</button>}</p>)}</section></>}
export function Configuration({onError}:{onError:(message:string)=>void}){const[content,setContent]=useState('streams: []\n');const[format,setFormat]=useState<'yaml'|'json'>('yaml');const[issues,setIssues]=useState<ConfigIssue[]>([]);const[versions,setVersions]=useState<ConfigVersion[]>([]);const candidate={format,content};const load=async()=>{try{const[config,history]=await Promise.all([api.config(),api.versions()]);setContent(JSON.stringify(config,null,2));setFormat('json');setVersions(history)}catch(cause){onError(errorMessage(cause))}};useEffect(()=>{void load()},[]);const validate=async()=>{try{setIssues((await api.validateConfig(candidate)).errors)}catch(cause){onError(errorMessage(cause))}};const saveDraft=async()=>{try{await api.saveDraft(candidate)}catch(cause){onError(errorMessage(cause))}};const publish=async()=>{try{await api.applyConfig(candidate);await load()}catch(cause){onError(errorMessage(cause))}};return <section className="panel config"><div className="panel-title"><h3>Configuration</h3><div className="actions"><select value={format} onChange={e=>setFormat(e.target.value as 'yaml'|'json')}><option value="yaml">YAML</option><option value="json">JSON</option></select><button onClick={()=>void saveDraft()}>Save draft</button><button onClick={()=>void validate()}>Validate</button><button onClick={()=>void publish()}>Publish</button></div></div><textarea aria-label="Configuration editor" value={content} onChange={e=>setContent(e.target.value)} spellCheck={false}/>{issues.map((issue,i)=><p className="error-row" key={i}><strong>{issue.path||'document'}</strong>: {issue.message}</p>)}<h3 className="subheading">Version history</h3>{versions.map(version=><div className="version" key={version.id}><span>{version.id} · {version.format}</span><button onClick={()=>window.confirm(`Rollback ${version.id}?`)&&void api.rollback(version.id).catch(cause=>onError(errorMessage(cause)))}>Rollback</button></div>)}</section>}
export function Components({onError}:{onError:(message:string)=>void}){const[items,setItems]=useState<Component[]>([]);const[schema,setSchema]=useState<unknown>();useEffect(()=>{Promise.all([api.components(),api.schema()]).then(([a,b])=>{setItems(a);setSchema(b)}).catch(cause=>onError(errorMessage(cause)))},[onError]);return <section className="panel"><div className="panel-title"><h3>Component catalogue</h3><span>{items.length} registered</span></div><div className="component-grid">{items.map(item=><article key={`${item.kind}-${item.name}`}><strong>{item.name}</strong><span>{item.kind}</span><p>{item.description??'No description'}</p></article>)}</div><h3 className="subheading">Schema and examples</h3><pre className="schema">{schema?JSON.stringify(schema,null,2):'Loading…'}</pre></section>}
export function Events({events}:{events:ControlEvent[]}){const[filter,setFilter]=useState('');const visible=events.filter(event=>!filter||`${event.event_type} ${event.stream_id??''} ${event.outcome} ${event.message??''}`.toLowerCase().includes(filter.toLowerCase()));return <section className="panel"><div className="panel-title"><h3>Events</h3><div className="actions"><input aria-label="Event filter" placeholder="Filter events" value={filter} onChange={event=>setFilter(event.target.value)}/><span>{visible.length} matching</span></div></div>{visible.length?visible.map((event,i)=><p className="event-row" key={i}><strong>{event.event_type}</strong> {event.stream_id??'system'} · {event.outcome} {event.operation_id?`· ${event.operation_id}`:''} {event.message??''}</p>):<p className="empty">No matching events.</p>}</section>}
export function Settings({status}:{status:EngineStatus|null}){return <section className="panel"><div className="panel-title"><h3>Settings</h3><span>Security and capability status</span></div><p>API version: v1</p><p>Backend: {status?.version??'Loading…'}</p><p>Polling: 5 seconds</p><p>Credentials are read from build-time environment configuration and never rendered in the UI.</p></section>}
function Card({label,value}:{label:string;value:string|number}){return <div className="card"><span>{label}</span><strong>{value}</strong></div>}
function errorMessage(cause:unknown){return typeof cause==='object'&&cause&&'message'in cause?String(cause.message):cause instanceof Error?cause.message:'Control API unavailable'}
