import { useEffect, useState } from 'react'
import { api, AuditRecord, ControlNode, Rollout, RolloutDetail } from '../api'

export function Rollouts({ nodes, onError }: { nodes: ControlNode[]; onError: (message: string) => void }) {
  const [items, setItems] = useState<Rollout[]>([]); const [selected, setSelected] = useState<RolloutDetail>(); const [version, setVersion] = useState(''); const [targets, setTargets] = useState<string[]>([]); const [batch, setBatch] = useState(1); const [busy, setBusy] = useState(false); const [audit, setAudit] = useState<AuditRecord[]>([])
  const refresh = async () => { try { const next = await api.rollouts(); setItems(next); if (selected) setSelected(await api.rollout(selected.rollout.rollout_id)) } catch (cause) { onError(message(cause)) } }
  useEffect(() => { void refresh() }, [])
  const create = async () => { if (!version.trim() || targets.length === 0) return; try { setBusy(true); const rollout = await api.createRollout(version.trim(), targets, batch); setItems(items => [rollout, ...items]); setSelected(await api.rollout(rollout.rollout_id)); setBusy(false) } catch (cause) { setBusy(false); onError(message(cause)) } }
  const action = async (id: string, operation: 'pause'|'resume'|'cancel'|'rollback') => { const rollbackVersion = operation === 'rollback' ? window.prompt('Rollback configuration version') ?? undefined : undefined; if (operation === 'rollback' && !rollbackVersion) return; try { setBusy(true); const rollout = await api.rolloutAction(id, operation, rollbackVersion); setSelected(await api.rollout(rollout.rollout_id)); await refresh(); setBusy(false) } catch (cause) { setBusy(false); onError(message(cause)) } }
  return <>
    <section className="panel"><div className="panel-title"><h3>Configuration rollouts</h3><span>{items.length} recorded</span></div><div className="toolbar"><input aria-label="Configuration version" placeholder="Configuration version" value={version} onChange={event => setVersion(event.target.value)}/><select aria-label="Rollout batch size" value={batch} onChange={event => setBatch(Number(event.target.value))}>{[1,2,5,10].map(value => <option key={value} value={value}>{value} per batch</option>)}</select><button disabled={busy || !version.trim() || targets.length === 0} onClick={() => void create()}>Create rollout</button></div><div className="node-picker">{nodes.map(node => <label key={node.id}><input type="checkbox" checked={targets.includes(node.id)} onChange={event => setTargets(current => event.target.checked ? [...current, node.id] : current.filter(id => id !== node.id))}/>{node.id} · {node.state}</label>)}</div>{items.length === 0 ? <p className="empty">No rollouts recorded.</p> : <div className="table">{items.map(item => <button className="rollout-row" key={item.rollout_id} onClick={() => void api.rollout(item.rollout_id).then(setSelected).catch(cause => onError(message(cause)))}><strong>{item.rollout_id}</strong><span>{item.config_version_id} · {item.current_batch + 1} / {Math.max(1, Math.ceil(item.total_targets / item.batch_size))} batches</span><span className={`state ${item.state}`}>{item.state}</span></button>)}</div>}</section>
    {selected && <RolloutDetailPanel detail={selected} audit={audit} setAudit={setAudit} busy={busy} onAction={action} onClose={() => setSelected(undefined)}/>} 
  </>
}

function RolloutDetailPanel({ detail, audit, setAudit, busy, onAction, onClose }: { detail: RolloutDetail; audit: AuditRecord[]; setAudit: (records: AuditRecord[]) => void; busy: boolean; onAction: (id: string, action: 'pause'|'resume'|'cancel'|'rollback') => void; onClose: () => void }) {
  useEffect(() => { void api.audit(detail.rollout.rollout_id).then(page => setAudit(page.items)).catch(() => setAudit([])) }, [detail.rollout.rollout_id, setAudit])
  const canAct = !['converged','cancelled','rolled_back'].includes(detail.rollout.state)
  return <section className="panel detail"><div className="panel-title"><div><span className="eyebrow">ROLLOUT DETAIL</span><h3>{detail.rollout.rollout_id}</h3></div><div className="actions"><button onClick={onClose}>Close</button>{canAct && <button disabled={busy} onClick={() => onAction(detail.rollout.rollout_id, detail.rollout.state === 'paused' ? 'resume' : 'pause')}>{detail.rollout.state === 'paused' ? 'Resume' : 'Pause'}</button>}{canAct && <button disabled={busy} onClick={() => onAction(detail.rollout.rollout_id, 'cancel')}>Cancel</button>}{canAct && <button disabled={busy} onClick={() => onAction(detail.rollout.rollout_id, 'rollback')}>Rollback</button>}</div></div><p><strong>{detail.rollout.config_version_id}</strong> · batch size {detail.rollout.batch_size} · {detail.rollout.state}</p><div className="table">{detail.targets.map(target => <div className="rollout-target" key={target.node_id}><strong>{target.node_id}</strong><span>{target.state}</span><small>{target.observed_config_version ?? 'target not observed'}{target.error ? ` · ${target.error}` : ''}</small></div>)}</div><h4>Audit history</h4>{audit.length ? audit.map(item => <div className="event-row" key={item.event_id}><strong>{item.action}</strong><span>{item.outcome} · {item.actor ?? 'unknown'}</span><small>{new Date(item.occurred_at_ms).toLocaleString()}</small></div>) : <p className="empty">No audit records.</p>}</section>
}

function message(cause: unknown) { return typeof cause === 'object' && cause && 'message' in cause ? String(cause.message) : cause instanceof Error ? cause.message : 'Control API unavailable' }
